coverage:
  precision: 2
  round: down
  range: "35...100"
  status:
    project:
      default:
        informational: true
    patch: off
fixes:
  - "ros_ws/src/ros2_controllers/::"
ignore:
  - "**/test"
comment:
  layout: "diff, flags, files"
  behavior: default
