// Copyright (c) 2025, PAL Robotics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef STATE_INTERFACES_BROADCASTER__STATE_INTERFACES_BROADCASTER_HPP_
#define STATE_INTERFACES_BROADCASTER__STATE_INTERFACES_BROADCASTER_HPP_

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "control_msgs/msg/float64_values.hpp"
#include "control_msgs/msg/keys.hpp"
#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_publisher.hpp"

// auto-generated by generate_parameter_library
#include "state_interfaces_broadcaster/state_interfaces_broadcaster_parameters.hpp"

namespace state_interfaces_broadcaster
{
/**
 * \brief State Interfaces Broadcaster for selected state interfaces in a ros2_control system.
 *
 * StateInterfacesBroadcaster publishes the selected state interfaces from ros2_control as ROS
 * messages.
 *
 * Publishes to:
 * - \b ~/names (control_msgs::msg::Keys): The list of the interface names that are selected
 * to be published by the interfaces state broadcaster. This is published with transient local
 * durability.
 * - \b ~/values (control_msgs::msg::Float64Values): The list of the values corresponding to the
 * interface names that are selected to be published by the interfaces state broadcaster.
 *
 * \note The values are published at the same rate as the controller update rate.
 */
class StateInterfacesBroadcaster : public controller_interface::ControllerInterface
{
public:
  StateInterfacesBroadcaster();

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  // Optional parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // publishers and messages
  std::shared_ptr<rclcpp::Publisher<control_msgs::msg::Keys>> names_publisher_;
  std::shared_ptr<rclcpp::Publisher<control_msgs::msg::Float64Values>> values_publisher_;
  std::shared_ptr<realtime_tools::RealtimePublisher<control_msgs::msg::Float64Values>>
    realtime_values_publisher_;
  control_msgs::msg::Keys names_msg_;
  control_msgs::msg::Float64Values values_msg_;
};

}  // namespace state_interfaces_broadcaster

#endif  // STATE_INTERFACES_BROADCASTER__STATE_INTERFACES_BROADCASTER_HPP_
