// Copyright (c) 2025, PAL Robotics
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef GENERIC_STATE_BROADCASTER__GENERIC_STATE_BROADCASTER_HPP_
#define GENERIC_STATE_BROADCASTER__GENERIC_STATE_BROADCASTER_HPP_

#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "control_msgs/msg/dynamic_joint_state.hpp"
#include "control_msgs/msg/string_array.hpp"
#include "control_msgs/msg/values_array.hpp"
#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_publisher.hpp"

// auto-generated by generate_parameter_library
#include "generic_state_broadcaster/generic_state_broadcaster_parameters.hpp"

namespace generic_state_broadcaster
{
/**
 * \brief Generic State Broadcaster for selected state interfaces in a ros2_control system.
 *
 * GenericStateBroadcaster publishes the selected state interfaces from ros2_control as ROS
 * messages.
 *
 * Publishes to:
 * - \b ~/names (control_msgs::msg::StringArray): The list of the interface names that are selected
 * to be published by the generic state broadcaster. This is published with transient local
 * durability.
 * - \b ~/values (control_msgs::msg::ValuesArray): The list of the values corresponding to the
 * interface names that are selected to be published by the generic state broadcaster.
 *
 * \note The values are published at the same rate as the controller update rate.
 */
class GenericStateBroadcaster : public controller_interface::ControllerInterface
{
public:
  GenericStateBroadcaster();

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  // Optional parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // publishers and messages
  std::shared_ptr<rclcpp::Publisher<control_msgs::msg::StringArray>> names_publisher_;
  std::shared_ptr<rclcpp::Publisher<control_msgs::msg::ValuesArray>> values_publisher_;
  std::shared_ptr<realtime_tools::RealtimePublisher<control_msgs::msg::ValuesArray>>
    realtime_values_publisher_;
  control_msgs::msg::ValuesArray values_msg_;
};

}  // namespace generic_state_broadcaster

#endif  // GENERIC_STATE_BROADCASTER__GENERIC_STATE_BROADCASTER_HPP_
