name: Coverage Build
on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: rolling
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          # build all packages listed in the meta package
          package-name:
            diff_drive_controller
            effort_controllers
            force_torque_sensor_broadcaster
            forward_command_controller
            joint_state_broadcaster
            joint_trajectory_controller
            gripper_controllers
            position_controllers
            ros2_controllers
            ros2_controllers_test_nodes
            velocity_controllers
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_controllers-not-released.${{ env.ROS_DISTRO }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          skip-tests: true
      - uses: codecov/codecov-action@v1.0.14
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
