name: Foxy Binary Build
# Build & test all dependencies from released (binary) packages.

on:
  pull_request:
    branches:
      - foxy
  push:
    branches:
      - foxy
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '08 18 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: foxy
      upstream_workspace: ros2_controllers-not-released.foxy.repos
      ref_for_scheduled_build: foxy
