<<<<<<< HEAD:.github/workflows/galactic-rhel-binary-build.yml
name: Galactic RHEL Binary Build
on:
  workflow_dispatch:
    branches:
      - galactic
  pull_request:
    branches:
      - galactic
  push:
=======
name: RHEL Iron Binary Build
on:
  workflow_dispatch:
  pull_request:
>>>>>>> 0bcb77b ([CI] debian + RHEL updates (#985)):.github/workflows/iron-rhel-binary-build.yml
    branches:
      - galactic
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  galactic_rhel_binary:
    name: Galactic RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: galactic
    container: ghcr.io/ros-controls/ros:galactic-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_controllers
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install -iyr --from-path src/ros2_controllers || true
      - name: Build and test
      # source also underlay workspace with generate_parameter_library on rhel9
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source /opt/ros2_ws/install/setup.bash
          colcon build --packages-skip rqt_joint_trajectory_controller
          colcon test --packages-skip rqt_joint_trajectory_controller
          colcon test-result --verbose
