name: Galactic Semi-Binary Build
# Build & test that compiles the main dependencies from source.

on:
  pull_request:
    branches:
      - galactic
  push:
    branches:
      - galactic
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 18 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: galactic
      upstream_workspace: ros2_controllers.galactic.repos
      ref_for_scheduled_build: galactic
