name: Humble Source Build
on:
  workflow_dispatch:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 4 * * *'

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: humble
      ref: humble
      ros2_repo_branch: humble
