name: RHEL Iron Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - iron
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  iron_rhel_binary:
    name: Iron RHEL binary build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rhel-binary-build.yml@master
    with:
      ros_distro: iron
      upstream_workspace: ros2_controllers.iron.repos
      ref_for_scheduled_build: iron
      skip_packages: rqt_joint_trajectory_controller
