name: Coverage Build - Jazzy
on:
  workflow_dispatch:
  pull_request: &event
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '.github/workflows/jazzy-coverage-build.yml'
      - '**.yaml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'codecov.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers.jazzy.repos'
  push: *event

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  coverage_jazzy:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: jazzy
