name: Kilted - ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - kilted
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.yaml'
      - '.github/workflows/kilted-abi-compatibility.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_controllers-not-released.kilted.repos'
      - '**.xml'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  abi_check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@master
    with:
      ros_distro: kilted
