name: Reusable Debian Source Build
# Reusable action to simplify dealing with debian source builds
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS2 distribution name'
        required: true
        type: string
      ref_for_scheduled_build:
        description: 'Reference on which the repo should be checkout for scheduled build. Usually is this name of a branch or a tag.'
        default: ''
        required: false
        type: string
      upstream_workspace:
        description: 'Path to local .repos file.'
        default: ''
        required: false
        type: string
      skip_packages:
        description: 'Packages to skip from build and test'
        default: ''
        required: false
        type: string


jobs:
  debian_source:
    name: ${{ inputs.ros_distro }} debian build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: ${{ inputs.ros_distro }}
      path: src/ros2_controllers
    container: ghcr.io/ros-controls/ros:${{ inputs.ros_distro }}-debian
    steps:
      - name: Checkout default ref when build is not scheduled
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.path }}
      - name: Checkout ${{ inputs.ref_for_scheduled_build }} on scheduled build
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref_for_scheduled_build }}
          path: ${{ env.path }}
      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros2_ws/install/setup.bash
          if [[ -n "${{ inputs.upstream_workspace }}" ]]; then
            vcs import src < ${{ env.path }}/${{ inputs.upstream_workspace }}
          fi
          colcon build --packages-up-to $(colcon list --paths ${{ env.path }}/* --names-only) --packages-skip ${{ inputs.skip_packages }}
      - name: Test workspace
        shell: bash
        continue-on-error: true
        run: |
          source /opt/ros2_ws/install/setup.bash
          colcon test --packages-select $(colcon list --paths ${{ env.path }}/* --names-only) --packages-skip ${{ inputs.skip_packages }}
          colcon test-result --verbose
