name: RHEL Rolling Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  rolling_rhel_binary:
    name: Rolling RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: rolling
      skip-packages: rqt_joint_trajectory_controller
    container: ghcr.io/ros-controls/ros:rolling-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_controllers
          # default behavior is correct on master branch
          # ref: ${{ github.event_name == 'schedule' && 'master' || '' }}
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install -iyr --from-path src/ros2_controllers || true
      - name: Build workspace
        # source also underlay workspace with generate_parameter_library on rhel9
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source /opt/ros2_ws/install/setup.bash
          colcon build  --packages-up-to $(colcon list --paths src/ros2_controllers/* --names-only) --packages-skip ${{ env.skip-packages }}
      - name: Test workspace
        shell: bash
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source /opt/ros2_ws/install/setup.bash
          colcon test --packages-select $(colcon list --paths src/ros2_controllers/* --names-only) --packages-skip  ${{ env.skip-packages }}
          colcon test-result --verbose
