name: Rolling Check Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '**.rst'
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.svg'
      - '**.yml'
      - '**.yaml'
<<<<<<< HEAD
=======
      - '!.github/**' # exclude yaml files in .github directory
      - '.github/workflows/rolling-check-docs.yml'
>>>>>>> 851f10a (Improve paths filtering of docs CI job (#1796))

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-docs:
    name: Check Docs
    uses: ros-controls/control.ros.org/.github/workflows/reusable-sphinx-check-single-version.yml@master
    with:
      ROS2_CONTROLLERS_PR: ${{ github.ref }}
