name: RHEL Rolling Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  rolling_rhel_binary:
    name: Rolling RHEL binary build
    uses: ./.github/workflows/reusable-rhel-binary-build.yml
    with:
      ros_distro: rolling
      upstream_workspace: ros2_controllers.rolling.repos
      ref_for_scheduled_build: master
      skip_packages: rqt_joint_trajectory_controller
