name: rosdoc2

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ros2_controllers/doc/**
      - ros2_controllers/rosdoc2.yaml
      - ros2_controllers/package.xml


jobs:
  check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rosdoc2.yml@master
